version: '3.8'
services:
        gateway:
                build: gateway
                image: gateway
                container_name: gateway
                ports:
                        - "8080:8080"
                depends_on:
                        - server
                environment:
                        - TZ=Europe/Yekaterinburg
                        - SHAREIT_SERVER_URL=http://server:9090

        server:
                build: server
                image: server
                container_name: server
                ports:
                        - "9090:9090"
                depends_on:
                        - db
                environment:
                        - DB_NAME=shareit
                        - POSTGRES_USER=root
                        - POSTGRES_PASSWORD=root
                        - DB_HOST=db
                        - DB_PORT=6541
                        - TZ=Europe/Yekaterinburg

        db:
                image: postgres:13.7-alpine
                container_name: db
                ports:
                        - "6541:5432"
                environment:
                        - TZ=TZ=Europe/Yekaterinburg
                        - POSTGRES_DB=shareit
                        - POSTGRES_USER=root
                        - POSTGRES_PASSWORD=root